name: Close Issue Action
description: This action closes an issue based on the number of issues a person has

inputs:
  number:
    required: true
  token: # token variable available in workflow as env var named INPUT_TOKEN
    required: true
    description: Token of the user that creates the issue
  author:
    required: true
  

runs:
  using: docker # we are saying this action will run on docker
  image: 'Dockerfile' # we will use our own Dockerfile to build an image and run it.

branding: #generates a logo for our action
  icon: arrow-down #icon of the image
  color: blue # background color of the logo of our action
