# every action has a name
name: Close Issue Action
# description
description: This action closes an issue based on the number of issues a person has
# input parameters to be taken from user
inputs:
  title: # name of variable. In action script it will be available in workflow as environment variable with name INPUT_TITLE
    required: true # required variable possible values are true or false
    description: Title of the issue
  token: # token variable available in workflow as env var named INPUT_TOKEN
    required: true
    description: Token of the user that creates the issue
  assignees: # available as INPUT_ASSIGNEES
    required: false
    description: Assignees of the issue
    default: '' # default value of variable if not provided
  body: # body as INPUT_BODY
    required: false
    default: ''
    description: Body of the issue

# definition how we want our action
runs:
  using: docker # we are saying this action will run on docker
  image: 'Dockerfile' # we will use our own Dockerfile to build an image and run it.

# for publishing purposes
branding: #generates a logo for our action
  icon: arrow-down #icon of the image
  color: blue # background color of the logo of our action
