name: Test Workflow
on:
  issue:
    types: [created]

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Run Action
        uses: ./
        with:
          number: ${{ github.event.number }}
          token: ${{secrets.GITHUB_TOKEN}} # default token in GitHub Workflow
          author: ${{ github.event.issues.user.login }}
